export default {
  GET_PRODUCTS_LIST_REQUEST_START: 'GET_PRODUCTS_LIST_REQUEST_START',
  GET_PRODUCTS_LIST_RESPONSE: 'GET_PRODUCTS_LIST_RESPONSE',

  GET_SINGLE_PRODUCT_REQUEST_START: 'GET_SINGLE_PRODUCT_REQUEST_START',
  GET_SINGLE_PRODUCT_RESPONSE: 'GET_SINGLE_PRODUCT_RESPONSE',

  CREATE_PRODUCT_REQUEST_START: 'CREATE_PRODUCT_REQUEST_START',
  CREATE_PRODUCT_RESPONSE: 'CREATE_PRODUCT_RESPONSE',

  UPDATE_PRODUCT_REQUEST_START: 'UPDATE_PRODUCT_REQUEST_START',
  UPDATE_PRODUCT_RESPONSE: 'UPDATE_PRODUCT_RESPONSE',

  DELETE_PRODUCT_REQUEST_START: 'DELETE_PRODUCTS_REQUEST_START',
  DELETE_PRODUCT_RESPONSE: 'DELETE_PRODUCTS_RESPONSE',

  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',

  CLEAR_SINGLE_PRODUCT: 'CLEAR_SINGLE_PRODUCT',

  HANDLE_ERROR: 'HANDLE_ERROR',

  CLEAR_ERROR: 'CLEAR_ERROR'
};